FROM node:22.14.0-alpine
WORKDIR /frontend

ARG VITE_API_URL
ARG VITE_SANCTUM_URL
ARG VITE_WEB_AS_ADMIN
ARG VITE_ENABLE_LOGIN

ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_SANCTUM_URL=${VITE_SANCTUM_URL}
ENV VITE_WEB_AS_ADMIN=${VITE_WEB_AS_ADMIN}
ENV VITE_ENABLE_LOGIN=${VITE_ENABLE_LOGIN}

COPY package.json package-lock.json ./
RUN npm install
RUN npm install -g serve

COPY . .
RUN npm run build

CMD serve -s dist